databases:
  - name: Animeview_mio_DB
    databaseName: animeview_db
    user: Animeview_mio
    region: singapore

services:
  - type: web
    name: Animeview_mio
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Animeview_mio_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false